import { useEffect, useRef, useState } from "react";
import { api } from "../api/client";
import type { AgentEvent, AgentEventsResponse, AgentStatus } from "../api/types";

const POLL_MS = 3000;
const MAX_EVENTS = 100;

// Polls the real autonomous agent (backend/app/services/agent.py) - every
// event returned here was generated by that background loop evaluating real
// Model-3 batches against real control limits, never invented client-side.
export function useAgentFeed() {
  const [events, setEvents] = useState<AgentEvent[]>([]);
  const [status, setStatus] = useState<AgentStatus | null>(null);
  const sinceId = useRef(0);

  useEffect(() => {
    let cancelled = false;

    const poll = () => {
      api
        .get<AgentEventsResponse>(`/api/agent/events?since_id=${sinceId.current}&limit=50`)
        .then((res) => {
          if (cancelled || res.events.length === 0) return;
          sinceId.current = res.latest_id;
          setEvents((prev) => [...res.events].reverse().concat(prev).slice(0, MAX_EVENTS));
        })
        .catch(() => void 0);

      api
        .get<AgentStatus>("/api/agent/status")
        .then((res) => !cancelled && setStatus(res))
        .catch(() => void 0);
    };

    poll();
    const id = setInterval(poll, POLL_MS);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, []);

  return { events, status };
}
