import type {
  ClassMetric,
  CostConfig,
  DefectDistributionEntry,
  FarFrrPoint,
  Machine,
  MachineIncident,
  MachineReading,
  ParamKey,
  ProductDefect,
  ProductionPoint,
  RobustnessCondition,
  StandardValue,
} from "./types.js";

export const MACHINES: Machine[] = [
  { id: "M1", name: "Hot Rolling Mill", status: "down" },
  { id: "M2", name: "Finishing Mill", status: "down" },
  { id: "M3", name: "Slitting Line", status: "warning" },
  { id: "M4", name: "Coiling Line", status: "running" },
  { id: "M5", name: "Pickling Line", status: "running" },
  { id: "M6", name: "Annealing Furnace", status: "warning" },
  { id: "M7", name: "Galvanizing Line", status: "running" },
  { id: "M8", name: "Temper Mill", status: "running" },
  { id: "M9", name: "Shearing Line", status: "running" },
  { id: "M10", name: "Recoiling Line", status: "running" },
  { id: "M11", name: "Inspection Station", status: "running" },
  { id: "M12", name: "Packaging Line", status: "running" },
];

export const MACHINE_READINGS: MachineReading[] = [
  { machineId: "M1", temperature: 38, pressure: 165, speed: 56, vibration: 3.2, recordedAt: "11:12 AM" },
  { machineId: "M2", temperature: 26, pressure: 190, speed: 57, vibration: 3.1, recordedAt: "11:12 AM" },
  { machineId: "M3", temperature: 24, pressure: 158, speed: 54, vibration: 4.6, recordedAt: "11:12 AM" },
  { machineId: "M4", temperature: 25, pressure: 161, speed: 55, vibration: 2.9, recordedAt: "11:12 AM" },
  { machineId: "M5", temperature: 24, pressure: 159, speed: 53, vibration: 2.6, recordedAt: "11:12 AM" },
  { machineId: "M6", temperature: 27, pressure: 163, speed: 63, vibration: 3.0, recordedAt: "11:12 AM" },
  { machineId: "M7", temperature: 25, pressure: 160, speed: 55, vibration: 2.8, recordedAt: "11:12 AM" },
  { machineId: "M8", temperature: 26, pressure: 162, speed: 56, vibration: 3.3, recordedAt: "11:12 AM" },
  { machineId: "M9", temperature: 24, pressure: 158, speed: 54, vibration: 2.7, recordedAt: "11:12 AM" },
  { machineId: "M10", temperature: 25, pressure: 161, speed: 55, vibration: 3.1, recordedAt: "11:12 AM" },
  { machineId: "M11", temperature: 25, pressure: 160, speed: 55, vibration: 2.9, recordedAt: "11:12 AM" },
  { machineId: "M12", temperature: 24, pressure: 159, speed: 54, vibration: 2.8, recordedAt: "11:12 AM" },
];

const BASE_PARAMS: Array<{ parameter: ParamKey; label: string; correctValue: number; min: number; max: number; unit: string }> = [
  { parameter: "temperature", label: "Temperature", correctValue: 25, min: 20, max: 30, unit: "°C" },
  { parameter: "pressure", label: "Rolling Pressure", correctValue: 160, min: 150, max: 170, unit: "bar" },
  { parameter: "speed", label: "Speed", correctValue: 55, min: 50, max: 60, unit: "m/min" },
  { parameter: "vibration", label: "Vibration", correctValue: 3, min: 2, max: 4, unit: "mm/s" },
];
const BASE_THICKNESS = { correctValue: 2.0, min: 1.95, max: 2.05, unit: "mm" };

export const STANDARD_VALUES: StandardValue[] = MACHINES.flatMap((m) => [
  ...BASE_PARAMS.map((p) => ({ machineId: m.id, ...p })),
  { machineId: m.id, parameter: "thickness" as const, label: "Thickness", ...BASE_THICKNESS },
]);

export const INCIDENTS: MachineIncident[] = [
  {
    id: "inc-m1-temperature-1",
    machineId: "M1",
    parameter: "temperature",
    label: "Temperature",
    expectedMin: 20,
    expectedMax: 30,
    actualValue: 38,
    unit: "°C",
    severity: "critical",
    emergency: true,
    status: "stopped",
    recommendedAction: "Stop machine and inspect cooling system",
    downtimeMinutes: 40,
    costPerMinute: 250,
    downtimeStart: "10:30 AM",
    downtimeEnd: "11:10 AM",
    date: "Today",
    acknowledged: true,
    maintenanceNotified: true,
  },
  {
    id: "inc-m2-pressure-1",
    machineId: "M2",
    parameter: "pressure",
    label: "Rolling Pressure",
    expectedMin: 150,
    expectedMax: 170,
    actualValue: 190,
    unit: "bar",
    severity: "critical",
    emergency: true,
    status: "stopped",
    recommendedAction: "Stop machine and release pressure valve",
    downtimeMinutes: 65,
    costPerMinute: 250,
    downtimeStart: "10:05 AM",
    downtimeEnd: "11:10 AM",
    date: "Today",
    acknowledged: true,
    maintenanceNotified: false,
  },
  {
    id: "inc-m3-vibration-1",
    machineId: "M3",
    parameter: "vibration",
    label: "Vibration",
    expectedMin: 2,
    expectedMax: 4,
    actualValue: 4.6,
    unit: "mm/s",
    severity: "warning",
    emergency: true,
    status: "acknowledged",
    recommendedAction: "Schedule bearing inspection before next shift",
    downtimeMinutes: 15,
    costPerMinute: 250,
    downtimeStart: "10:50 AM",
    date: "Today",
    acknowledged: true,
    maintenanceNotified: false,
  },
  {
    id: "inc-m6-speed-1",
    machineId: "M6",
    parameter: "speed",
    label: "Speed",
    expectedMin: 50,
    expectedMax: 60,
    actualValue: 63,
    unit: "m/min",
    severity: "warning",
    emergency: false,
    status: "open",
    recommendedAction: "Recalibrate drive controller",
    downtimeMinutes: 5,
    costPerMinute: 250,
    date: "Today",
    acknowledged: false,
    maintenanceNotified: false,
  },
  {
    id: "inc-m3-vibration-0",
    machineId: "M3",
    parameter: "vibration",
    label: "Vibration",
    expectedMin: 2,
    expectedMax: 4,
    actualValue: 7.1,
    unit: "mm/s",
    severity: "warning",
    emergency: false,
    status: "resolved",
    recommendedAction: "Inspect roller bearings",
    downtimeMinutes: 30,
    costPerMinute: 250,
    downtimeStart: "2:10 PM",
    downtimeEnd: "2:40 PM",
    date: "Yesterday",
    acknowledged: true,
    maintenanceNotified: true,
  },
  {
    id: "inc-m2-pressure-0",
    machineId: "M2",
    parameter: "pressure",
    label: "Rolling Pressure",
    expectedMin: 150,
    expectedMax: 170,
    actualValue: 182,
    unit: "bar",
    severity: "critical",
    emergency: true,
    status: "resolved",
    recommendedAction: "Stop machine and release pressure valve",
    downtimeMinutes: 35,
    costPerMinute: 250,
    downtimeStart: "9:00 AM",
    downtimeEnd: "9:35 AM",
    date: "Yesterday",
    acknowledged: true,
    maintenanceNotified: true,
  },
];

export const PRODUCT_DEFECTS: ProductDefect[] = [
  {
    productId: "P003",
    machineId: "M1",
    defectType: "Thickness",
    targetValue: 2.0,
    actualValue: 2.35,
    unit: "mm",
    reworkedQuantity: 2,
    scrappedQuantity: 0,
    recordedAt: "Today · 9:40 AM",
    machineParametersAtProduction: { temperature: 38, pressure: 162, speed: 55, vibration: 3.0 },
    confidence: 0.89,
    location: "Center, 50% width",
    reviewStatus: "auto",
    source: "seed" as const,
  },
  {
    productId: "P005",
    machineId: "M2",
    defectType: "Thickness",
    targetValue: 2.0,
    actualValue: 2.31,
    unit: "mm",
    reworkedQuantity: 0,
    scrappedQuantity: 5,
    recordedAt: "Today · 10:04 AM",
    machineParametersAtProduction: { temperature: 26, pressure: 190, speed: 57, vibration: 6.8 },
    confidence: 0.94,
    location: "Left edge, 8% width",
    reviewStatus: "auto",
    source: "seed" as const,
  },
  {
    productId: "P007",
    machineId: "M3",
    defectType: "Thickness",
    targetValue: 2.0,
    actualValue: 2.2,
    unit: "mm",
    reworkedQuantity: 1,
    scrappedQuantity: 0,
    recordedAt: "Today · 10:22 AM",
    machineParametersAtProduction: { temperature: 24, pressure: 158, speed: 54, vibration: 4.6 },
    confidence: 0.81,
    location: "Center, 46% width",
    reviewStatus: "auto",
    source: "seed" as const,
  },
  {
    productId: "P009",
    machineId: "M3",
    defectType: "Thickness",
    targetValue: 2.0,
    actualValue: 2.4,
    unit: "mm",
    reworkedQuantity: 0,
    scrappedQuantity: 5,
    recordedAt: "Today · 10:47 AM",
    machineParametersAtProduction: { temperature: 24, pressure: 159, speed: 55, vibration: 6.9 },
    confidence: 0.97,
    location: "Right edge, 91% width",
    reviewStatus: "auto",
    source: "seed" as const,
  },
  {
    productId: "P011",
    machineId: "M4",
    defectType: "Thickness",
    targetValue: 2.0,
    actualValue: 2.06,
    unit: "mm",
    reworkedQuantity: 0,
    scrappedQuantity: 0,
    recordedAt: "Today · 11:02 AM",
    machineParametersAtProduction: { temperature: 25, pressure: 161, speed: 55, vibration: 2.9 },
    confidence: 0.68,
    location: "Center, 52% width",
    reviewStatus: "pending_review",
    source: "seed" as const,
  },
  {
    productId: "P013",
    machineId: "M2",
    defectType: "Thickness",
    targetValue: 2.0,
    actualValue: 2.22,
    unit: "mm",
    reworkedQuantity: 3,
    scrappedQuantity: 0,
    recordedAt: "Today · 11:08 AM",
    machineParametersAtProduction: { temperature: 26, pressure: 188, speed: 56, vibration: 3.4 },
    confidence: 0.86,
    location: "Left edge, 14% width",
    reviewStatus: "auto",
    source: "seed" as const,
  },
  {
    productId: "P015",
    machineId: "M5",
    defectType: "Surface",
    targetValue: 2.0,
    actualValue: 2.03,
    unit: "mm",
    reworkedQuantity: 0,
    scrappedQuantity: 0,
    recordedAt: "Today · 11:15 AM",
    // All four machine parameters are within normal range -- there's no
    // obvious correlated cause. Deviation is small too. The classifier
    // flagged it anyway on a surface pattern it hasn't seen before, which
    // is exactly the "novel condition" case: low confidence isn't always
    // about deviation size. Rework/scrap quantities are left at 0 (unknown)
    // until a human confirms this is a real defect.
    machineParametersAtProduction: { temperature: 24, pressure: 159, speed: 53, vibration: 2.6 },
    confidence: 0.59,
    location: "Center, 55% width",
    reviewStatus: "pending_review",
    source: "seed" as const,
  },
];

export const PRODUCTION_TREND: ProductionPoint[] = [
  { time: "06:00", production: 720, good: 674, defective: 46 },
  { time: "07:00", production: 760, good: 710, defective: 50 },
  { time: "08:00", production: 810, good: 757, defective: 53 },
  { time: "09:00", production: 845, good: 790, defective: 55 },
  { time: "10:00", production: 880, good: 826, defective: 54 },
  { time: "11:00", production: 905, good: 855, defective: 50 },
  { time: "12:00", production: 890, good: 842, defective: 48 },
  { time: "13:00", production: 860, good: 816, defective: 44 },
  { time: "14:00", production: 900, good: 858, defective: 42 },
  { time: "15:00", production: 930, good: 890, defective: 40 },
  { time: "16:00", production: 910, good: 872, defective: 38 },
  { time: "17:00", production: 895, good: 859, defective: 36 },
];

export const DEFECT_DISTRIBUTION: DefectDistributionEntry[] = [
  { category: "Thickness", units: 260 },
  { category: "Surface", units: 150 },
  { category: "Temperature", units: 90 },
  { category: "Pressure", units: 40 },
  { category: "Other", units: 16 },
];

export const CLASS_METRICS: ClassMetric[] = [
  { category: "Thickness", precision: 0.94, recall: 0.91, f1: 0.925, support: 260 },
  { category: "Surface", precision: 0.88, recall: 0.85, f1: 0.865, support: 150 },
  { category: "Temperature", precision: 0.9, recall: 0.93, f1: 0.915, support: 90 },
  { category: "Pressure", precision: 0.86, recall: 0.8, f1: 0.829, support: 40 },
  { category: "Other", precision: 0.71, recall: 0.63, f1: 0.668, support: 16 },
];

export const CONFUSION_LABELS = ["Thickness", "Surface", "Temperature", "Pressure", "Other"];

export const CONFUSION_MATRIX: number[][] = [
  [237, 9, 6, 5, 3],
  [11, 128, 5, 4, 2],
  [3, 2, 84, 1, 0],
  [3, 3, 2, 32, 0],
  [2, 2, 1, 1, 10],
];

export const ROBUSTNESS_CONDITIONS: RobustnessCondition[] = [
  { condition: "Baseline (day shift, calibrated sensors)", sampleSize: 4820, accuracy: 0.962, note: "Reference condition" },
  { condition: "Night shift (Shift C, low ambient light)", sampleSize: 1140, accuracy: 0.941, note: "Slight recall drop on surface defects" },
  { condition: "New coil spec (2.2mm target)", sampleSize: 380, accuracy: 0.918, note: "Fewer training examples at this target" },
  { condition: "Sensor drift, 30+ days since calibration", sampleSize: 610, accuracy: 0.903, note: "Threshold recalibration recommended" },
  { condition: "High ambient vibration (nearby line running)", sampleSize: 265, accuracy: 0.887, note: "Elevated false-accepts on vibration-linked defects" },
];

export const FAR_FRR_CURVE: FarFrrPoint[] = [
  { threshold: 0.5, far: 0.021, frr: 0.061 },
  { threshold: 0.55, far: 0.018, frr: 0.068 },
  { threshold: 0.6, far: 0.015, frr: 0.076 },
  { threshold: 0.65, far: 0.013, frr: 0.086 },
  { threshold: 0.7, far: 0.011, frr: 0.098 },
  { threshold: 0.75, far: 0.009, frr: 0.114 },
  { threshold: 0.8, far: 0.007, frr: 0.135 },
  { threshold: 0.85, far: 0.005, frr: 0.163 },
  { threshold: 0.9, far: 0.004, frr: 0.204 },
  { threshold: 0.95, far: 0.002, frr: 0.271 },
];

export const HEATMAP_HOURS = PRODUCTION_TREND.map((p) => p.time);

const normal = { severity: "normal" as const };
const warn = (note: string) => ({ severity: "warning" as const, note });
const crit = (note: string) => ({ severity: "critical" as const, note });

export const HEATMAP_ROWS: Record<string, Array<{ severity: string; note?: string }>> = {
  M1: [normal, normal, normal, normal, warn("Temperature 33°C"), crit("Temperature 38°C"), crit("Temperature 37°C"), warn("Temperature 32°C"), normal, normal, normal, normal],
  M2: [normal, normal, normal, warn("Pressure 178 bar"), crit("Pressure 190 bar"), crit("Pressure 187 bar"), crit("Pressure 182 bar"), warn("Pressure 176 bar"), normal, normal, normal, normal],
  M3: [normal, normal, normal, normal, normal, warn("Vibration 4.6 mm/s"), warn("Vibration 4.8 mm/s"), warn("Vibration 4.5 mm/s"), warn("Vibration 4.3 mm/s"), normal, normal, normal],
  M4: [normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal],
  M5: [normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal],
  M6: [normal, normal, normal, normal, normal, normal, normal, warn("Speed 63 m/min"), warn("Speed 62 m/min"), normal, normal, normal],
  M7: [normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal],
  M8: [normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal],
  M9: [normal, normal, warn("Vibration 4.4 mm/s"), normal, normal, normal, normal, normal, normal, normal, normal, normal],
  M10: [normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal],
  M11: [normal, normal, normal, normal, normal, normal, normal, normal, normal, warn("Pressure 172 bar"), normal, normal],
  M12: [normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal, normal],
};

export const COST_CONFIG: CostConfig = {
  downtimeCostPerMinute: 250,
  manufacturingCostPerUnit: 400,
  reworkCostPerUnit: 250,
};
